<?php

/**
 * @file
 * Primary module hooks for ewp_institutions_domains module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_form_id_form_alter().
 */
function ewp_institutions_domains_form_user_register_form_alter(array &$form, FormStateInterface &$form_state, $form_id) {
  $form_alter = \Drupal::service('ewp_institutions_domains.form_alter');
  $form_alter->userFormAlter($form, $form_state, $form_id);
}
