<?php

/**
 * @file
 * Primary module hooks for ewp_institutions_assignment module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\ewp_institutions_assignment\Event\UserCreatedWithValidDomainEvent;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function ewp_institutions_assignment_user_presave(EntityInterface $user) {
  if (empty($user->original)) {
    /** @var \Drupal\user\UserInterface $user */
    $mail = explode('@', $user->getEmail());

    $domain_handler = \Drupal::service('ewp_institutions_domains');
    $matches = $domain_handler->getMatches($mail[1]);

    if ($matches) {
      $list_id = \array_keys($matches)[0];
      $hei_id = $domain_handler->getList($list_id)->heiId();

      // Instantiate our event.
      $event = new UserCreatedWithValidDomainEvent($user, $mail[1], $hei_id);
      $event_name = UserCreatedWithValidDomainEvent::EVENT_NAME;

      // Dispatch the event.
      $event_dispatcher = \Drupal::service('event_dispatcher');
      $event_dispatcher->dispatch($event, $event_name);
    }
  }
}
